sudo: false
language: node_js
node_js:
  - "8.10"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn install

script:
  - yarn lint
  - yarn test:coverage
  - codecov

notifications:
  email: false